#include "book_management.h"
#include "util.h"
#include <stdlib.h>
#include <strings.h>
#include <string.h>
#include <stdio.h>




//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file){
    file=fopen("libraryBooks.txt","wb");
  if(file==NULL){
    printf("!!!!ERROR THE FILE IS NULL");
    return -1;
  }
  int i=0;
  while(i<booksLibrary.length){
    fwrite(&booksLibrary.array,sizeof(struct Book),1,file);
    i++;
  }
  fclose(file);
  return 0;
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
  while(true){
    struct Book book;
    if(fread(&booksLibrary,sizeof(struct Book),1,file)!=1){
      printf("could not read the file");
      break;
    }
    add_book_to_array(&booksLibrary,book);
  }
  return 0;
}


//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(struct Book book){
    int i;
    for(i=0;i < booksLibrary.length;i++){
    if(equalBooks(book,booksLibrary.array[i])){
           booksLibrary.array[i].copies+=book.copies;
           return 0;
        }
        return -1;
    }
    return 0;
}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(struct Book book){

    int i,pos=findBook(book,&booksLibrary);
    if(pos==-1){
        printf("Wrong index");
    }else{
    for(i = pos; i < booksLibrary.length; i++){
        if(existsBook(book, &booksLibrary)){
            booksLibrary.array[i]= booksLibrary.array[i+1];
            booksLibrary.length--;
            //the book is successfully removed.
            printf("!~~~~~~~~~~~~~~Booked removed~~~~~~~~~~~~~~~~~!" );

        }
    }
           return -1;
  }
  return 0;
}


//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_title (const char *title){
	struct BookArray newBooksLibrary;
	newBooksLibrary.length = 0;
	newBooksLibrary.array = NULL;
	int j;
	///if the number of books in library is zero
	if(booksLibrary.length==0){
		//return null;
		return newBooksLibrary;
	}
	//for all the books in library
	for(j=0;j<booksLibrary.length;j++){
		//compare the title with the title of the books in library
		if(strcasecmp(title,booksLibrary.array[j].title)==0){
			//if the titles are the same
			//reallocate the found book in newBooksLibrary;
			       add_book_to_array(&newBooksLibrary,booksLibrary.array[j]);
		}
	}
	return newBooksLibrary;
}

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_author (const char *author){
	struct BookArray newBooksLibrary;
	newBooksLibrary.length = 0;
	newBooksLibrary.array = NULL;
	int j;
	///if the number of books in library is zero
	if(booksLibrary.length==0){
		//return null;
		return newBooksLibrary;
	}
	//for all the books in library
	for(j=0;j<booksLibrary.length;j++){
		//compare the title with the title of the books in library
		if(strcasecmp(author,booksLibrary.array[j].authors)==0){
			//if the titles are the same
			//reallocate the found book in newBooksLibrary;
			       add_book_to_array(&newBooksLibrary,booksLibrary.array[j]);
		}
	}
	return newBooksLibrary;
}

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
struct BookArray find_book_by_year (unsigned int year){
	struct BookArray newBooksLibrary;
	newBooksLibrary.length = 0;
	newBooksLibrary.array = NULL;
	int j;
	///if the number of books in library is zero
	if(booksLibrary.length==0){
		//return null;
		return newBooksLibrary;
	}
	//for all the books in library
	for(j=0;j<booksLibrary.length;j++){
		//compare the title with the title of the books in library
		if(booksLibrary.array[j].year==year){
			//if the titles are the same
			//reallocate the found book in newBooksLibrary;
			       add_book_to_array(&newBooksLibrary,booksLibrary.array[j]);
		}
	}
	return newBooksLibrary;
}
